FROM eclipse-temurin:17-jdk-alpine
COPY microservices-api-gateway-0.0.1-SNAPSHOT.jar microservices-api-gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservices-api-gateway-0.0.1-SNAPSHOT.jar"]