FROM eclipse-temurin:17-jdk-alpine
COPY microservices-length-exchange-service-0.0.1-SNAPSHOT.jar microservices-length-exchange-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservices-length-exchange-service-0.0.1-SNAPSHOT.jar"]