FROM eclipse-temurin:17-jdk-alpine
COPY microservices-service-registry-0.0.1-SNAPSHOT.jar microservices-service-registry-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "microservices-service-registry-0.0.1-SNAPSHOT.jar"]